version: '3.9'

services:
  database:
    container_name: didomi
    image: mysql:8.0.32
    restart: unless-stopped
    command:
      [
        '--default-authentication-plugin=mysql_native_password',
        '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
        '--lower_case_table_names=1',
      ]
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - didomi:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

volumes:
  didomi:
